-- Auto-generated compatibility patch
-- Generated by Factorio Mod Harmonizer
-- Resolves 1 conflict(s)

-- Patch: PATCH_BURNER-INSERTER_COMPAT
-- Description: Conditional recipe modification for burner-inserter to resolve mod conflicts
-- Fixes: CRITICAL_RECIPE_BURNER-INSERTER


-- Compatibility patch for burner-inserter
-- Fixes conflict between: bobelectronics, bobvehicleequipment, bobassembly, bobtech, bobpower, bobinserters, bobwarfare, bobores, boblibrary, bobgreenhouse, bobequipment, bobenemies, bobmining, Krastorio2-spaced-out, boblogistics, bobmodules, bobrevamp, bobplates, base

if data.raw.recipe["burner-inserter"] then
    local recipe = data.raw.recipe["burner-inserter"]
    
    -- Check available ingredients and choose appropriate version
    if data.raw.item["wood-gear-wheel"] and not data.raw.item["kr-steel-gear-wheel"] then
        -- Lignumis context: use wood gear
        recipe.ingredients = {
            {type = "item", name = "iron-plate", amount = 1},
            {type = "item", name = "wood-gear-wheel", amount = 1}
        }
    elseif data.raw.item["kr-steel-gear-wheel"] then
        -- Krastorio2 context: use steel gear but add fallback
        recipe.ingredients = {
            {type = "item", name = "iron-plate", amount = 1},
            {type = "item", name = "kr-steel-gear-wheel", amount = 1}
        }
        
        -- Add alternative recipe for wood planets
        if data.raw.item["wood-gear-wheel"] then
            data:extend({{
                type = "recipe",
                name = "burner-inserter-wood",
                enabled = true,
                ingredients = {
                    {type = "item", name = "iron-plate", amount = 1},
                    {type = "item", name = "wood-gear-wheel", amount = 1}
                },
                results = {{type = "item", name = "burner-inserter", amount = 1}}
            }})
        end
    end
end

