-- Auto-generated compatibility patch
-- Generated by Factorio Mod Harmonizer
-- Resolves 15 conflict(s)

-- Patch: PATCH_TREE-SEEDING_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for tree-seeding with 3 alternative research paths
-- Fixes: MISSING_DEPS_TREE-SEEDING


-- Comprehensive research compatibility patch for tree-seeding
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["tree-seeding"] then
    local tech = data.raw.technology["tree-seeding"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "tree-seeding-basic",
        icon = tech.icon,
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "tree-seeding-advanced",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "tree-seeding-space",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_ELECTRONICS_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for electronics with 3 alternative research paths
-- Fixes: MISSING_DEPS_ELECTRONICS


-- Comprehensive research compatibility patch for electronics
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["electronics"] then
    local tech = data.raw.technology["electronics"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "electronics-basic",
        icon = tech.icon,
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "electronics-advanced",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "electronics-space",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_STEAM-POWER_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for steam-power with 3 alternative research paths
-- Fixes: MISSING_DEPS_STEAM-POWER


-- Comprehensive research compatibility patch for steam-power
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["steam-power"] then
    local tech = data.raw.technology["steam-power"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "steam-power-basic",
        icon = tech.icon,
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "steam-power-advanced",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "steam-power-space",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_LANDFILL_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for landfill with 3 alternative research paths
-- Fixes: MISSING_DEPS_LANDFILL


-- Comprehensive research compatibility patch for landfill
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["landfill"] then
    local tech = data.raw.technology["landfill"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "landfill-basic",
        icon = tech.icon,
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "landfill-advanced",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "landfill-space",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_WORKER-ROBOTS-SPEED-1_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for worker-robots-speed-1 with 3 alternative research paths
-- Fixes: MISSING_DEPS_WORKER-ROBOTS-SPEED-1


-- Comprehensive research compatibility patch for worker-robots-speed-1
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["worker-robots-speed-1"] then
    local tech = data.raw.technology["worker-robots-speed-1"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "worker-robots-speed-1-basic",
        icon = tech.icon,
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "worker-robots-speed-1-advanced",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "worker-robots-speed-1-space",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_WORKER-ROBOTS-SPEED-2_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for worker-robots-speed-2 with 3 alternative research paths
-- Fixes: MISSING_DEPS_WORKER-ROBOTS-SPEED-2


-- Comprehensive research compatibility patch for worker-robots-speed-2
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["worker-robots-speed-2"] then
    local tech = data.raw.technology["worker-robots-speed-2"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "worker-robots-speed-2-basic",
        icon = tech.icon,
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "worker-robots-speed-2-advanced",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "worker-robots-speed-2-space",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_WORKER-ROBOTS-SPEED-3_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for worker-robots-speed-3 with 3 alternative research paths
-- Fixes: MISSING_DEPS_WORKER-ROBOTS-SPEED-3


-- Comprehensive research compatibility patch for worker-robots-speed-3
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["worker-robots-speed-3"] then
    local tech = data.raw.technology["worker-robots-speed-3"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "worker-robots-speed-3-basic",
        icon = tech.icon,
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "worker-robots-speed-3-advanced",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "worker-robots-speed-3-space",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_WORKER-ROBOTS-SPEED-4_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for worker-robots-speed-4 with 3 alternative research paths
-- Fixes: MISSING_DEPS_WORKER-ROBOTS-SPEED-4


-- Comprehensive research compatibility patch for worker-robots-speed-4
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["worker-robots-speed-4"] then
    local tech = data.raw.technology["worker-robots-speed-4"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "worker-robots-speed-4-basic",
        icon = tech.icon,
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "worker-robots-speed-4-advanced",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "worker-robots-speed-4-space",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_PHYSICAL-PROJECTILE-DAMAGE-1_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for physical-projectile-damage-1 with 3 alternative research paths
-- Fixes: MISSING_DEPS_PHYSICAL-PROJECTILE-DAMAGE-1


-- Comprehensive research compatibility patch for physical-projectile-damage-1
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["physical-projectile-damage-1"] then
    local tech = data.raw.technology["physical-projectile-damage-1"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "physical-projectile-damage-1-basic",
        icon = tech.icon,
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "physical-projectile-damage-1-advanced",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "physical-projectile-damage-1-space",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_PHYSICAL-PROJECTILE-DAMAGE-2_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for physical-projectile-damage-2 with 3 alternative research paths
-- Fixes: MISSING_DEPS_PHYSICAL-PROJECTILE-DAMAGE-2


-- Comprehensive research compatibility patch for physical-projectile-damage-2
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["physical-projectile-damage-2"] then
    local tech = data.raw.technology["physical-projectile-damage-2"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "physical-projectile-damage-2-basic",
        icon = tech.icon,
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "physical-projectile-damage-2-advanced",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "physical-projectile-damage-2-space",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_WEAPON-SHOOTING-SPEED-2_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for weapon-shooting-speed-2 with 3 alternative research paths
-- Fixes: MISSING_DEPS_WEAPON-SHOOTING-SPEED-2


-- Comprehensive research compatibility patch for weapon-shooting-speed-2
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["weapon-shooting-speed-2"] then
    local tech = data.raw.technology["weapon-shooting-speed-2"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "weapon-shooting-speed-2-basic",
        icon = tech.icon,
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "weapon-shooting-speed-2-advanced",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "weapon-shooting-speed-2-space",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_PHYSICAL-PROJECTILE-DAMAGE-3_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for physical-projectile-damage-3 with 3 alternative research paths
-- Fixes: MISSING_DEPS_PHYSICAL-PROJECTILE-DAMAGE-3


-- Comprehensive research compatibility patch for physical-projectile-damage-3
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["physical-projectile-damage-3"] then
    local tech = data.raw.technology["physical-projectile-damage-3"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "physical-projectile-damage-3-basic",
        icon = tech.icon,
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "physical-projectile-damage-3-advanced",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "physical-projectile-damage-3-space",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_WEAPON-SHOOTING-SPEED-3_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for weapon-shooting-speed-3 with 3 alternative research paths
-- Fixes: MISSING_DEPS_WEAPON-SHOOTING-SPEED-3


-- Comprehensive research compatibility patch for weapon-shooting-speed-3
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["weapon-shooting-speed-3"] then
    local tech = data.raw.technology["weapon-shooting-speed-3"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "weapon-shooting-speed-3-basic",
        icon = tech.icon,
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "weapon-shooting-speed-3-advanced",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "weapon-shooting-speed-3-space",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_PHYSICAL-PROJECTILE-DAMAGE-4_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for physical-projectile-damage-4 with 3 alternative research paths
-- Fixes: MISSING_DEPS_PHYSICAL-PROJECTILE-DAMAGE-4


-- Comprehensive research compatibility patch for physical-projectile-damage-4
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["physical-projectile-damage-4"] then
    local tech = data.raw.technology["physical-projectile-damage-4"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "physical-projectile-damage-4-basic",
        icon = tech.icon,
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "physical-projectile-damage-4-advanced",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "physical-projectile-damage-4-space",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_WEAPON-SHOOTING-SPEED-4_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for weapon-shooting-speed-4 with 3 alternative research paths
-- Fixes: MISSING_DEPS_WEAPON-SHOOTING-SPEED-4


-- Comprehensive research compatibility patch for weapon-shooting-speed-4
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["weapon-shooting-speed-4"] then
    local tech = data.raw.technology["weapon-shooting-speed-4"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "weapon-shooting-speed-4-basic",
        icon = tech.icon,
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "weapon-shooting-speed-4-advanced",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "weapon-shooting-speed-4-space",
            icon = tech.icon,
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end

