-- Auto-generated compatibility patch
-- Generated by Factorio Mod Harmonizer
-- Resolves 29 conflict(s)

-- Patch: PATCH_BURNER-INSERTER_ALL_VARIANTS
-- Description: Recipe expansion for burner-inserter - adds all mod variants as additional recipes
-- Fixes: AVAILABILITY_BURNER-INSERTER


-- Comprehensive recipe expansion for burner-inserter
-- Adds mod-specific recipe variants alongside original recipes
-- Affected mods: base, lignumis
-- Severity: CRITICAL

-- Create additional recipe variants for each mod


-- Base Game variant of burner-inserter
if data.raw.recipe["burner-inserter"] then
    local base_variant = table.deepcopy(data.raw.recipe["burner-inserter"])
    base_variant.name = "burner-inserter-base-variant"
    base_variant.localised_name = {"", "burner-inserter", " (Base Game Style)"}
    base_variant.enabled = true
    base_variant.order = (base_variant.order or "a") .. "-base-variant"
    base_variant.hidden = false

    base_variant.ingredients = {{type="item", name="iron-plate", amount=1}, {type="item", name="iron-gear-wheel", amount=1}}
    base_variant.results = {{type="item", name="burner-inserter", amount=1}}
    
    data:extend({base_variant})
end

-- Lignumis variant of burner-inserter
if data.raw.recipe["burner-inserter"] then
    local lignumis_variant = table.deepcopy(data.raw.recipe["burner-inserter"])
    lignumis_variant.name = "burner-inserter-lignumis-variant"
    lignumis_variant.localised_name = {"", "burner-inserter", " (Lignumis Style)"}
    lignumis_variant.enabled = true
    lignumis_variant.order = (lignumis_variant.order or "a") .. "-lignumis-variant"
    lignumis_variant.hidden = false

    lignumis_variant.ingredients = {{type="item", name="wooden-gear-wheel", amount=1}, {type="item", name="lumber", amount=1}}
    lignumis_variant.results = {{type="item", name="burner-inserter", amount=1}}
    
    data:extend({lignumis_variant})
end

-- Keep ALL original recipes active - no disabling!
-- Players can now choose between:
-- 1. Original burner-inserter (current winner of mod conflicts)
-- 2. burner-inserter-base-variant (Base Game style)
-- 2. burner-inserter-lignumis-variant (Lignumis style)


-- Patch: PATCH_FAST-INSERTER_ALL_VARIANTS
-- Description: Recipe expansion for fast-inserter - adds all mod variants as additional recipes
-- Fixes: MISSING_DEPS_FAST-INSERTER


-- Comprehensive recipe expansion for fast-inserter
-- Adds mod-specific recipe variants alongside original recipes
-- Affected mods: base
-- Severity: HIGH

-- Create additional recipe variants for each mod


-- Base Game variant of fast-inserter
if data.raw.recipe["fast-inserter"] then
    local base_variant = table.deepcopy(data.raw.recipe["fast-inserter"])
    base_variant.name = "fast-inserter-base-variant"
    base_variant.localised_name = {"", "fast-inserter", " (Base Game Style)"}
    base_variant.enabled = true
    base_variant.order = (base_variant.order or "a") .. "-base-variant"
    base_variant.hidden = false

    base_variant.ingredients = {{type="item", name="inserter", amount=1}, {type="item", name="electronic-circuit", amount=2}}
    base_variant.results = {{type="item", name="fast-inserter", amount=1}}
    
    data:extend({base_variant})
end

-- Keep ALL original recipes active - no disabling!
-- Players can now choose between:
-- 1. Original fast-inserter (current winner of mod conflicts)
-- 2. fast-inserter-base-variant (Base Game style)


-- Patch: PATCH_FAST-TRANSPORT-BELT_ALL_VARIANTS
-- Description: Recipe expansion for fast-transport-belt - adds all mod variants as additional recipes
-- Fixes: MISSING_DEPS_FAST-TRANSPORT-BELT


-- Comprehensive recipe expansion for fast-transport-belt
-- Adds mod-specific recipe variants alongside original recipes
-- Affected mods: base
-- Severity: HIGH

-- Create additional recipe variants for each mod


-- Base Game variant of fast-transport-belt
if data.raw.recipe["fast-transport-belt"] then
    local base_variant = table.deepcopy(data.raw.recipe["fast-transport-belt"])
    base_variant.name = "fast-transport-belt-base-variant"
    base_variant.localised_name = {"", "fast-transport-belt", " (Base Game Style)"}
    base_variant.enabled = true
    base_variant.order = (base_variant.order or "a") .. "-base-variant"
    base_variant.hidden = false

    base_variant.ingredients = {{type="item", name="transport-belt", amount=1}, {type="item", name="iron-gear-wheel", amount=5}}
    base_variant.results = {{type="item", name="fast-transport-belt", amount=1}}
    
    data:extend({base_variant})
end

-- Keep ALL original recipes active - no disabling!
-- Players can now choose between:
-- 1. Original fast-transport-belt (current winner of mod conflicts)
-- 2. fast-transport-belt-base-variant (Base Game style)


-- Patch: PATCH_EXPRESS-TRANSPORT-BELT_ALL_VARIANTS
-- Description: Recipe expansion for express-transport-belt - adds all mod variants as additional recipes
-- Fixes: MISSING_DEPS_EXPRESS-TRANSPORT-BELT


-- Comprehensive recipe expansion for express-transport-belt
-- Adds mod-specific recipe variants alongside original recipes
-- Affected mods: base
-- Severity: HIGH

-- Create additional recipe variants for each mod


-- Base Game variant of express-transport-belt
if data.raw.recipe["express-transport-belt"] then
    local base_variant = table.deepcopy(data.raw.recipe["express-transport-belt"])
    base_variant.name = "express-transport-belt-base-variant"
    base_variant.localised_name = {"", "express-transport-belt", " (Base Game Style)"}
    base_variant.enabled = true
    base_variant.order = (base_variant.order or "a") .. "-base-variant"
    base_variant.hidden = false

    base_variant.ingredients = {{type="item", name="fast-transport-belt", amount=1}, {type="item", name="iron-gear-wheel", amount=10}, {type="fluid", name="lubricant", amount=20}}
    base_variant.results = {{type="item", name="express-transport-belt", amount=1}}
    
    data:extend({base_variant})
end

-- Keep ALL original recipes active - no disabling!
-- Players can now choose between:
-- 1. Original express-transport-belt (current winner of mod conflicts)
-- 2. express-transport-belt-base-variant (Base Game style)


-- Patch: PATCH_UNDERGROUND-BELT_ALL_VARIANTS
-- Description: Recipe expansion for underground-belt - adds all mod variants as additional recipes
-- Fixes: MISSING_DEPS_UNDERGROUND-BELT


-- Comprehensive recipe expansion for underground-belt
-- Adds mod-specific recipe variants alongside original recipes
-- Affected mods: base
-- Severity: HIGH

-- Create additional recipe variants for each mod


-- Base Game variant of underground-belt
if data.raw.recipe["underground-belt"] then
    local base_variant = table.deepcopy(data.raw.recipe["underground-belt"])
    base_variant.name = "underground-belt-base-variant"
    base_variant.localised_name = {"", "underground-belt", " (Base Game Style)"}
    base_variant.enabled = true
    base_variant.order = (base_variant.order or "a") .. "-base-variant"
    base_variant.hidden = false

    base_variant.ingredients = {{type="item", name="transport-belt", amount=5}, {type="item", name="iron-plate", amount=10}}
    base_variant.results = {{type="item", name="underground-belt", amount=2}}
    
    data:extend({base_variant})
end

-- Keep ALL original recipes active - no disabling!
-- Players can now choose between:
-- 1. Original underground-belt (current winner of mod conflicts)
-- 2. underground-belt-base-variant (Base Game style)


-- Patch: PATCH_SPLITTER_ALL_VARIANTS
-- Description: Recipe expansion for splitter - adds all mod variants as additional recipes
-- Fixes: MISSING_DEPS_SPLITTER


-- Comprehensive recipe expansion for splitter
-- Adds mod-specific recipe variants alongside original recipes
-- Affected mods: base
-- Severity: HIGH

-- Create additional recipe variants for each mod


-- Base Game variant of splitter
if data.raw.recipe["splitter"] then
    local base_variant = table.deepcopy(data.raw.recipe["splitter"])
    base_variant.name = "splitter-base-variant"
    base_variant.localised_name = {"", "splitter", " (Base Game Style)"}
    base_variant.enabled = true
    base_variant.order = (base_variant.order or "a") .. "-base-variant"
    base_variant.hidden = false

    base_variant.ingredients = {{type="item", name="transport-belt", amount=4}, {type="item", name="electronic-circuit", amount=5}, {type="item", name="iron-plate", amount=5}}
    base_variant.results = {{type="item", name="splitter", amount=1}}
    
    data:extend({base_variant})
end

-- Keep ALL original recipes active - no disabling!
-- Players can now choose between:
-- 1. Original splitter (current winner of mod conflicts)
-- 2. splitter-base-variant (Base Game style)


-- Patch: PATCH_PROCESSING-UNIT_ALL_VARIANTS
-- Description: Recipe expansion for processing-unit - adds all mod variants as additional recipes
-- Fixes: MISSING_DEPS_PROCESSING-UNIT


-- Comprehensive recipe expansion for processing-unit
-- Adds mod-specific recipe variants alongside original recipes
-- Affected mods: base
-- Severity: HIGH

-- Create additional recipe variants for each mod


-- Base Game variant of processing-unit
if data.raw.recipe["processing-unit"] then
    local base_variant = table.deepcopy(data.raw.recipe["processing-unit"])
    base_variant.name = "processing-unit-base-variant"
    base_variant.localised_name = {"", "processing-unit", " (Base Game Style)"}
    base_variant.enabled = true
    base_variant.order = (base_variant.order or "a") .. "-base-variant"
    base_variant.hidden = false

    base_variant.ingredients = {{type="item", name="electronic-circuit", amount=20}, {type="item", name="advanced-circuit", amount=2}, {type="fluid", name="sulfuric-acid", amount=5}}
    base_variant.results = {{type="item", name="processing-unit", amount=1}}
    
    data:extend({base_variant})
end

-- Keep ALL original recipes active - no disabling!
-- Players can now choose between:
-- 1. Original processing-unit (current winner of mod conflicts)
-- 2. processing-unit-base-variant (Base Game style)


-- Patch: PATCH_ELECTRONICS_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for electronics with 3 alternative research paths
-- Fixes: MISSING_DEPS_ELECTRONICS


-- Comprehensive research compatibility patch for electronics
-- Fixes conflict between: base, lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["electronics"] then
    local tech = data.raw.technology["electronics"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "electronics-basic",
        icon = tech.icon or "__base__/graphics/technology/automation.png",
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "electronics-advanced",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "electronics-space",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_ADVANCED-ELECTRONICS_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for advanced-electronics with 3 alternative research paths
-- Fixes: MISSING_DEPS_ADVANCED-ELECTRONICS


-- Comprehensive research compatibility patch for advanced-electronics
-- Fixes conflict between: base
-- Severity: HIGH

if data.raw.technology["advanced-electronics"] then
    local tech = data.raw.technology["advanced-electronics"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "advanced-electronics-basic",
        icon = tech.icon or "__base__/graphics/technology/automation.png",
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "advanced-electronics-advanced",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "advanced-electronics-space",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_ADVANCED-ELECTRONICS-2_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for advanced-electronics-2 with 3 alternative research paths
-- Fixes: MISSING_DEPS_ADVANCED-ELECTRONICS-2


-- Comprehensive research compatibility patch for advanced-electronics-2
-- Fixes conflict between: base
-- Severity: HIGH

if data.raw.technology["advanced-electronics-2"] then
    local tech = data.raw.technology["advanced-electronics-2"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "advanced-electronics-2-basic",
        icon = tech.icon or "__base__/graphics/technology/automation.png",
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "advanced-electronics-2-advanced",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "advanced-electronics-2-space",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_ROCKET-SILO_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for rocket-silo with 3 alternative research paths
-- Fixes: MISSING_DEPS_ROCKET-SILO


-- Comprehensive research compatibility patch for rocket-silo
-- Fixes conflict between: base
-- Severity: HIGH

if data.raw.technology["rocket-silo"] then
    local tech = data.raw.technology["rocket-silo"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "rocket-silo-basic",
        icon = tech.icon or "__base__/graphics/technology/automation.png",
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "rocket-silo-advanced",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "rocket-silo-space",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_TREE-SEEDING_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for tree-seeding with 3 alternative research paths
-- Fixes: MISSING_DEPS_TREE-SEEDING


-- Comprehensive research compatibility patch for tree-seeding
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["tree-seeding"] then
    local tech = data.raw.technology["tree-seeding"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "tree-seeding-basic",
        icon = tech.icon or "__base__/graphics/technology/automation.png",
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "tree-seeding-advanced",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "tree-seeding-space",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_STEAM-POWER_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for steam-power with 3 alternative research paths
-- Fixes: MISSING_DEPS_STEAM-POWER


-- Comprehensive research compatibility patch for steam-power
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["steam-power"] then
    local tech = data.raw.technology["steam-power"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "steam-power-basic",
        icon = tech.icon or "__base__/graphics/technology/automation.png",
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "steam-power-advanced",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "steam-power-space",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_LANDFILL_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for landfill with 3 alternative research paths
-- Fixes: MISSING_DEPS_LANDFILL


-- Comprehensive research compatibility patch for landfill
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["landfill"] then
    local tech = data.raw.technology["landfill"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "landfill-basic",
        icon = tech.icon or "__base__/graphics/technology/automation.png",
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "landfill-advanced",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "landfill-space",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_WORKER-ROBOTS-SPEED-1_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for worker-robots-speed-1 with 3 alternative research paths
-- Fixes: MISSING_DEPS_WORKER-ROBOTS-SPEED-1


-- Comprehensive research compatibility patch for worker-robots-speed-1
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["worker-robots-speed-1"] then
    local tech = data.raw.technology["worker-robots-speed-1"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "worker-robots-speed-1-basic",
        icon = tech.icon or "__base__/graphics/technology/automation.png",
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "worker-robots-speed-1-advanced",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "worker-robots-speed-1-space",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_WORKER-ROBOTS-SPEED-2_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for worker-robots-speed-2 with 3 alternative research paths
-- Fixes: MISSING_DEPS_WORKER-ROBOTS-SPEED-2


-- Comprehensive research compatibility patch for worker-robots-speed-2
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["worker-robots-speed-2"] then
    local tech = data.raw.technology["worker-robots-speed-2"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "worker-robots-speed-2-basic",
        icon = tech.icon or "__base__/graphics/technology/automation.png",
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "worker-robots-speed-2-advanced",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "worker-robots-speed-2-space",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_WORKER-ROBOTS-SPEED-3_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for worker-robots-speed-3 with 3 alternative research paths
-- Fixes: MISSING_DEPS_WORKER-ROBOTS-SPEED-3


-- Comprehensive research compatibility patch for worker-robots-speed-3
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["worker-robots-speed-3"] then
    local tech = data.raw.technology["worker-robots-speed-3"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "worker-robots-speed-3-basic",
        icon = tech.icon or "__base__/graphics/technology/automation.png",
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "worker-robots-speed-3-advanced",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "worker-robots-speed-3-space",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_WORKER-ROBOTS-SPEED-4_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for worker-robots-speed-4 with 3 alternative research paths
-- Fixes: MISSING_DEPS_WORKER-ROBOTS-SPEED-4


-- Comprehensive research compatibility patch for worker-robots-speed-4
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["worker-robots-speed-4"] then
    local tech = data.raw.technology["worker-robots-speed-4"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "worker-robots-speed-4-basic",
        icon = tech.icon or "__base__/graphics/technology/automation.png",
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "worker-robots-speed-4-advanced",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "worker-robots-speed-4-space",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_PHYSICAL-PROJECTILE-DAMAGE-1_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for physical-projectile-damage-1 with 3 alternative research paths
-- Fixes: MISSING_DEPS_PHYSICAL-PROJECTILE-DAMAGE-1


-- Comprehensive research compatibility patch for physical-projectile-damage-1
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["physical-projectile-damage-1"] then
    local tech = data.raw.technology["physical-projectile-damage-1"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "physical-projectile-damage-1-basic",
        icon = tech.icon or "__base__/graphics/technology/automation.png",
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "physical-projectile-damage-1-advanced",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "physical-projectile-damage-1-space",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_PHYSICAL-PROJECTILE-DAMAGE-2_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for physical-projectile-damage-2 with 3 alternative research paths
-- Fixes: MISSING_DEPS_PHYSICAL-PROJECTILE-DAMAGE-2


-- Comprehensive research compatibility patch for physical-projectile-damage-2
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["physical-projectile-damage-2"] then
    local tech = data.raw.technology["physical-projectile-damage-2"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "physical-projectile-damage-2-basic",
        icon = tech.icon or "__base__/graphics/technology/automation.png",
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "physical-projectile-damage-2-advanced",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "physical-projectile-damage-2-space",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_WEAPON-SHOOTING-SPEED-2_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for weapon-shooting-speed-2 with 3 alternative research paths
-- Fixes: MISSING_DEPS_WEAPON-SHOOTING-SPEED-2


-- Comprehensive research compatibility patch for weapon-shooting-speed-2
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["weapon-shooting-speed-2"] then
    local tech = data.raw.technology["weapon-shooting-speed-2"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "weapon-shooting-speed-2-basic",
        icon = tech.icon or "__base__/graphics/technology/automation.png",
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "weapon-shooting-speed-2-advanced",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "weapon-shooting-speed-2-space",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_PHYSICAL-PROJECTILE-DAMAGE-3_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for physical-projectile-damage-3 with 3 alternative research paths
-- Fixes: MISSING_DEPS_PHYSICAL-PROJECTILE-DAMAGE-3


-- Comprehensive research compatibility patch for physical-projectile-damage-3
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["physical-projectile-damage-3"] then
    local tech = data.raw.technology["physical-projectile-damage-3"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "physical-projectile-damage-3-basic",
        icon = tech.icon or "__base__/graphics/technology/automation.png",
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "physical-projectile-damage-3-advanced",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "physical-projectile-damage-3-space",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_WEAPON-SHOOTING-SPEED-3_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for weapon-shooting-speed-3 with 3 alternative research paths
-- Fixes: MISSING_DEPS_WEAPON-SHOOTING-SPEED-3


-- Comprehensive research compatibility patch for weapon-shooting-speed-3
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["weapon-shooting-speed-3"] then
    local tech = data.raw.technology["weapon-shooting-speed-3"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "weapon-shooting-speed-3-basic",
        icon = tech.icon or "__base__/graphics/technology/automation.png",
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "weapon-shooting-speed-3-advanced",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "weapon-shooting-speed-3-space",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_PHYSICAL-PROJECTILE-DAMAGE-4_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for physical-projectile-damage-4 with 3 alternative research paths
-- Fixes: MISSING_DEPS_PHYSICAL-PROJECTILE-DAMAGE-4


-- Comprehensive research compatibility patch for physical-projectile-damage-4
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["physical-projectile-damage-4"] then
    local tech = data.raw.technology["physical-projectile-damage-4"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "physical-projectile-damage-4-basic",
        icon = tech.icon or "__base__/graphics/technology/automation.png",
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "physical-projectile-damage-4-advanced",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "physical-projectile-damage-4-space",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_WEAPON-SHOOTING-SPEED-4_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for weapon-shooting-speed-4 with 3 alternative research paths
-- Fixes: MISSING_DEPS_WEAPON-SHOOTING-SPEED-4


-- Comprehensive research compatibility patch for weapon-shooting-speed-4
-- Fixes conflict between: lignumis, lignumis
-- Severity: HIGH

if data.raw.technology["weapon-shooting-speed-4"] then
    local tech = data.raw.technology["weapon-shooting-speed-4"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "weapon-shooting-speed-4-basic",
        icon = tech.icon or "__base__/graphics/technology/automation.png",
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "weapon-shooting-speed-4-advanced",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "weapon-shooting-speed-4-space",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_AUTOMATION_RESEARCH_COMPREHENSIVE
-- Description: Comprehensive research compatibility patch for automation with 3 alternative research paths
-- Fixes: MOD_TECH_CONFLICT_AUTOMATION


-- Comprehensive research compatibility patch for automation
-- Fixes conflict between: base, lignumis
-- Severity: HIGH

if data.raw.technology["automation"] then
    local tech = data.raw.technology["automation"]
    local original_prerequisites = tech.prerequisites or {}
    local original_unit = tech.unit
    local original_effects = tech.effects or {}
    
    -- Store original technology for reference
    local base_prerequisites = original_prerequisites
    local base_unit = original_unit
    local base_effects = original_effects
    
    -- Fallback: Create universal alternative research paths
    -- Alternative 1: Basic research path
    data:extend({{
        type = "technology",
        name = "automation-basic",
        icon = tech.icon or "__base__/graphics/technology/automation.png",
        icon_size = tech.icon_size or 256,
        prerequisites = {"automation"},
        unit = {
            count = 25,
            ingredients = {
                {"automation-science-pack", 1}
            },
            time = 10
        },
        effects = tech.effects or {}
    }})
    
    -- Alternative 2: Advanced research path
    if data.raw.technology["logistic-science-pack"] then
        data:extend({{
            type = "technology",
            name = "automation-advanced",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"automation", "logistic-science-pack"},
            unit = {
                count = 100,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1}
                },
                time = 30
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Alternative 3: Space-age compatible path
    if data.raw.technology["space-science-pack"] then
        data:extend({{
            type = "technology",
            name = "automation-space",
            icon = tech.icon or "__base__/graphics/technology/automation.png",
            icon_size = tech.icon_size or 256,
            prerequisites = {"space-science-pack"},
            unit = {
                count = 200,
                ingredients = {
                    {"automation-science-pack", 1},
                    {"logistic-science-pack", 1},
                    {"chemical-science-pack", 1},
                    {"space-science-pack", 1}
                },
                time = 60
            },
            effects = tech.effects or {}
        }})
    end
    
    -- Ensure original technology remains accessible
    if not tech.prerequisites or #tech.prerequisites == 0 then
        tech.prerequisites = {"automation"}
    end
end


-- Patch: PATCH_WOOD_GENERIC
-- Description: Generic compatibility patch for item wood
-- Fixes: CONFLICT_ITEM_WOOD


-- Generic compatibility patch for wood
-- Fixes conflict between: base, lignumis
-- Severity: MEDIUM
-- Type: item


if data.raw.item["wood"] then
    local item = data.raw.item["wood"]
    
    -- Ensure item compatibility across mods
    -- Create alternative versions if needed
    
    -- Alternative 1: Basic version
    data:extend({{
        type = "item",
        name = "wood-basic",
        icon = item.icon or "__base__/graphics/icons/iron-plate.png",
        icon_size = item.icon_size or 64,
        stack_size = item.stack_size or 100,
        subgroup = item.subgroup or "intermediate-product",
        order = (item.order or "a") .. "-basic"
    }})
    
    -- Alternative 2: Advanced version
    data:extend({{
        type = "item",
        name = "wood-advanced",
        icon = item.icon or "__base__/graphics/icons/steel-plate.png",
        icon_size = item.icon_size or 64,
        stack_size = math.max(1, math.floor((item.stack_size or 100) * 0.5)),
        subgroup = item.subgroup or "intermediate-product",
        order = (item.order or "a") .. "-advanced"
    }})
end


-- Patch: PATCH_COPPER-PLATE_GENERIC
-- Description: Generic compatibility patch for item copper-plate
-- Fixes: CONFLICT_ITEM_COPPER-PLATE


-- Generic compatibility patch for copper-plate
-- Fixes conflict between: base, lignumis
-- Severity: MEDIUM
-- Type: item


if data.raw.item["copper-plate"] then
    local item = data.raw.item["copper-plate"]
    
    -- Ensure item compatibility across mods
    -- Create alternative versions if needed
    
    -- Alternative 1: Basic version
    data:extend({{
        type = "item",
        name = "copper-plate-basic",
        icon = item.icon or "__base__/graphics/icons/iron-plate.png",
        icon_size = item.icon_size or 64,
        stack_size = item.stack_size or 100,
        subgroup = item.subgroup or "intermediate-product",
        order = (item.order or "a") .. "-basic"
    }})
    
    -- Alternative 2: Advanced version
    data:extend({{
        type = "item",
        name = "copper-plate-advanced",
        icon = item.icon or "__base__/graphics/icons/steel-plate.png",
        icon_size = item.icon_size or 64,
        stack_size = math.max(1, math.floor((item.stack_size or 100) * 0.5)),
        subgroup = item.subgroup or "intermediate-product",
        order = (item.order or "a") .. "-advanced"
    }})
end


-- Patch: PATCH_ELECTRONIC-CIRCUIT_GENERIC
-- Description: Generic compatibility patch for item electronic-circuit
-- Fixes: CONFLICT_ITEM_ELECTRONIC-CIRCUIT


-- Generic compatibility patch for electronic-circuit
-- Fixes conflict between: base, lignumis
-- Severity: MEDIUM
-- Type: item


if data.raw.item["electronic-circuit"] then
    local item = data.raw.item["electronic-circuit"]
    
    -- Ensure item compatibility across mods
    -- Create alternative versions if needed
    
    -- Alternative 1: Basic version
    data:extend({{
        type = "item",
        name = "electronic-circuit-basic",
        icon = item.icon or "__base__/graphics/icons/iron-plate.png",
        icon_size = item.icon_size or 64,
        stack_size = item.stack_size or 100,
        subgroup = item.subgroup or "intermediate-product",
        order = (item.order or "a") .. "-basic"
    }})
    
    -- Alternative 2: Advanced version
    data:extend({{
        type = "item",
        name = "electronic-circuit-advanced",
        icon = item.icon or "__base__/graphics/icons/steel-plate.png",
        icon_size = item.icon_size or 64,
        stack_size = math.max(1, math.floor((item.stack_size or 100) * 0.5)),
        subgroup = item.subgroup or "intermediate-product",
        order = (item.order or "a") .. "-advanced"
    }})
end

